ged2dot.py
test/test.py

Hi,
This pull request removed useles and unwanted return type for DescendantsLayout.filter_families and also made sure error are printed on stderr (and not stdout via standard print).
Regards,
Colin Chargy

Errors should be printed on stderr 

---

core/Makefile
core/TODO.adoc
core/requirements.txt
core/tests/level3.ged
core/tests/no_surname.ged
core/tests/test_core.py
core/tests/unexpected_date.ged

- Test missing surname/family name
- Test that we ignore a 3rd level
- Test that we just ignore a date which is not birth/death
- Test export of a no-husband/wife model
Statement coverage goes up to 100%.
Change-Id: I8e4a9c29e5aca90331bf4291801f7a766a55f2bd

Add remaining missing tests

---

TODO
ged2dot.py

This was working for .ged files from ancestry.com, but is not
necessarily true and we know the proper type anyway.
Change-Id: I61b57fce6b8be3e439d8832685771435b5ec25d8

Relax pointless requirement that individual/family starts with P/F

---

TODO
ged2dot.py
tests/test_ged2dot.py

In case CWD, dir(ged2dot.py) and dir(input.ged) are 3 different dirs, we
already handled placeholders relative to dir(ged2dot.py).
Be consistent and handle real images relative to dir(input.ged).
Change-Id: I2ad2105c947b4d8163d7446c5db87e1751edb5ca

Make sure that imagedir is relative to the gedcom's dir

---

qged2dot.py

This just had the wrong button title on Linux (which I didn't notice),
but it just doesn't allow specifying a filename on macOS.
Change-Id: I90a9d9f90c79928ff90ccdb8ed412611c87265ca

qt: png/dot should be a save dialog

---

ged2dot.py
qged2dot.py

Which would mean implicitly decoding with the system-default charset,
which is ascii on macOS.
Change-Id: Ifb0cba9f40557972c8fd248ee5e6613cf94a0dfd

qged2dot: kill last place where we opened a file in non-binary mode

---

README.adoc
tools/pack.bat

Similar to macOS, let the platform package manager install it instead.
This way pyinstaller now produces a working installation set, just need
to zip it up, which is a manual action for now.
Change-Id: Ia6d6c87a78fd09bb8574b6557abfc8187caf999c

qged2dot: give up on bundling dot for now

---

qged2dot.py

It seems 0..3 typically results in almost no edges, larger values don't
provide that.
Change-Id: I73a0ccab9219ce824458bbba1ee579602242d355

qged2dot: default to familydepth==3

---

ged2dot.py

hi, i've a GenoPro 2.0.1.6 generated GED file, it contains bare `1 CHILDREN` lines, so i guess the parse should look for whole words, not only substrings.

match to whole word tokens

---

ged2dot.py
tests/test_ged2dot.py

qged2dot already did this
Change-Id: Ie1f522a766cc28779429181f8ae1922f7cdded7d

ged2dot: default to familydepth==3

---

ged2dot.py
tests/no-cr.ged
tests/test_ged2dot.py

Python3 use "universal newlines" so users shouldn't have to care.

Support both \r\n and \n

---

NEWS.adoc
ged2dot.py

PNG output was fine without this already and is unchanged.
This is 1) of <https://github.com/vmiklos/ged2dot/issues/170>.
Patch-by: humaita
Change-Id: I66cbcc0a48b78dacc1e92a41d92940a3d54c8272

Keep aspect ratio of images in the PDF output with long names

---

ged2dot.py

Different default fonts don't play nicely with fake centering.
This is 3) of <https://github.com/vmiklos/ged2dot/issues/170>.
Patch-by: humaita
Change-Id: Ia7e701c5f4a8695f8906d502d09a75167afc6baf

Specify the font used for text explicitly

---

.pylintrc
ged2dot.py
tests/test_ged2dot.py

We still default to e.g. "1942-", but this allows specifying
--birthformat '* {}'
to do what was requested in the issue, trying to make everyone happy.
Related to 4) of <https://github.com/vmiklos/ged2dot/issues/170>.
Change-Id: Iebcf1a810eff36effd4f3ca96b55072e68823879

Add --birthformat option

---

Makefile

The old approach tried to check the changed modules, but this resulted
in hiding some errors in incremental builds. check-mypy takes a few
seconds only, it's better to just check all modules all the time.
Change-Id: I83c873ea9fa974b6aa5917d8124bf6d213434202

mypy: check all modules together

---

ged2dot.py
tests/test_ged2dot.py

Explicitly specify the height/width from the SVG, this is needed for the
PNG output.
See
<https://github.com/vmiklos/ged2dot/issues/179#issuecomment-992038773>.
Change-Id: Icb7b2e20f0556624a8c59e1c79285f68fcb1a858

dot export: fix non-centered marriage icon when no date is given

---

qged2dot.py

Regression from commit 1f1c3755f07cb9b971d10dda93f1819269f6c63f (Update
pylint to 2.12.2, 2021-12-22).
Change-Id: I94d3492ffe84aa742c43054ff0da8d44b743fa11

qged2dot: fix typo, % was unwanted before F<num>

---

README.adoc

Seems this can't be a problem on Windows/macOS, where the upstream
installer includes it by default.
Resolves <https://github.com/vmiklos/ged2dot/issues/200>.
Change-Id: I8c8c82dc7101a77c241ac1f13490338180629d4c

doc: mention the libreoffice python subpackages for install

---

ged2dot.py
tests/empty.ged
tests/test_ged2dot.py

Sample output:
Exception: Root family 'F1' is not found. First valid family would be '41'.
Related to <https://github.com/vmiklos/ged2dot/issues/201>.
Change-Id: I06ef7898e8306361bfe883fe7d926ed2ce8e3379

Fail nicer when the specified root family doesn't exist

---

README.adoc
libreoffice/HACKING

- require the oldest version upstream still supports
- test with the newer version
Change-Id: I0d738252a94d3de2f3d542bd1d56efefe6a23244

libreoffice: bump version numbers

---

.github/workflows/tests.yml
HACKING.adoc
Makefile
qged2dot.py

Python 3.6 is EOL since 23 Dec 2021, and openSUSE stable provides 3.9,
so let's jump to that version.
Change-Id: I2890e7fb4a226609c0bea426ead57db73e2b69fa

Update to Python 3.9

---

NEWS.adoc
ged2dot.py
ged2dotrc.sample
tests/test_ged2dot.py

Useful when wanting to show the descendants of a family (i.e. not
ancestors).
Change-Id: I2b940e347771c0832714111e421df3971ea29389

Add new direction config option to visit the graph only down, not up+down

---

Makefile
libreoffice/dialog.py
libreoffice/importer.py
requirements.txt

Newer flake8 doesn't see them and libreoffice bundles 3.8 anyway today
(towards 7.5).
Change-Id: I672e46a5d06492c99112a6e69f3cdcb1ff30b691

libreoffice: avoid type hints as comments for variables

---

ged2dot.py
guide/src/news.md
tools/fuzz.py

The expectation is only Ged2DotException is thrown, to be in sync with
the safe_*() functions.
Change-Id: I0717cd054da37df2e85f6cf2b4da4096189f6f38

Fix unexpected ValueError when the root family is not found

---

requirements.txt
tests/test_ged2dot.py

And fix the new mypy errors by not reusing the `stream` variable for
multiple purposes.

Update dependencies (2025-01)
