vmiklos/ged2dot

.gitignore
ged2dot.py

Hi!
I added support for input and output encoding as I needed this for my last name ;)
and in case of a wrong config all possible config parameters are printed to stderr.
I hope you like those changes
Regards

Encoding and Help

---

ged2dot.py

Fixes for individuals with missing data.  These changes were required to avoid errors with a GEDCOM I downloaded from ancestry.com.

Bug fixes for individuals with missing data

---

README.adoc
ged2dot.py

Also separate config file errors from data file errors. Finally add handling for conditions of unexpected .ged data by warning on line error and line number. (this can happen, for instance, when the sex of a particular ancestor is not filled in or unknown.)
Add a little bit more help to README

add better error handling and error out on lack of rc file

---

TODO
ged2dot.py
ged2dotrc.sample
test/nosex.ged
test/test.py

add explicit --help or -h flag to show usage
add ability to change border box width around nodes
add a sample ged2dotrc.sample
add the beginnings of a test for nosex.ged, but unsure how to finish it and link it in to assert true on failure

Add help and drawing dh

---

NEWS

Change-Id: I9e66e4fdb9b1af3d064096f880c3f5f5473e20d8

Fix a typo

---

.github/workflows/notifyirc.yml

Change-Id: I51ee2e67b50905a55500cd1d4917674569aad937

Experiment with IRC notification

---

.github/workflows/tests.yml

That's what I have locally.
Change-Id: If1132c4e2da82d7309bee343dda557803cc7f839

CI: update to Python 3.6

---

requirements.txt

Change-Id: Iec8bbaad21d3ae8720a2cdb3cce2dc6a43bc1321

Update pylint to 2.6.0

---

.github/workflows/tests.yml
README.adoc

Change-Id: I69932e2bb5f2b7cba873d1fb1167ec21dde96861

CI: be consistent wrt tests vs Tests

---

core/Makefile
core/README.adoc
core/TODO.adoc
core/core.py

Change-Id: I8d7c769a12818511b1809bcc0f3a6b38e3074cf5

Initial import of 'ged2dot core'

---

core/core.py

Change-Id: Ibd1d695e03a5d3a4adff396af11e5108dd5a8733

ged2dot core: avoid too many instance attributes in Individual

---

core/core.py

Change-Id: I8c47f170127853ca3ab506fe3623d465219e7c36

ged2dot core: avoid too many instance attributes in Family

---

core/core.py

And split up the monster function into readable pieces.
Change-Id: I5fd6ab92731b2003ab44e7aea35838a8e80240ea

ged2dot core: turn import_gedcom() into a class

---

core/core.py
core/tests/bom.ged
core/tests/test_core.py

Coverage goes up to 95%.
Change-Id: I83ad75f40ff14bde7a3a2d33e4ec245d1d655ec4

ged2dot core: add a BOM testcase

---

core/tests/test_core.py

Coverage goes up to 96%.
Change-Id: I12778c28c93453e105d8f000b3deb8fe859f4769

ged2dot core: add a graph limit testcase

---

core/core.py
core/tests/nosex.ged
core/tests/test_core.py

Change-Id: I594eb6f0ffd5294e5ec845746ed34dee9c6b2a64

ged2dot core: fix import error when sex is omitted

---

core/.coveragerc
core/core.py
core/tests/test_core.py

Coverage goes up to 97%.
Change-Id: Ifd746852f69f9a65d47df3fc9ffed0308fa905ea

ged2dot core: test color of an individual

---

core/tests/test_core.py

Coverage goes up to 98%.
Change-Id: Ib27b4cb1764ed4100ed3ce2cd397eb458a462b8c

ged2dot core: test default options

---

core/tests/hello.ged
core/tests/no_wife.ged
core/tests/test_core.py

Change-Id: I1cd8f499550cc9754339bf97a3c1cc92d948bd3b

Add test for the no-wife case

---

core/tests/no_husband.ged
core/tests/test_core.py

Coverage goes up to 98%.
Change-Id: I9f524bdeab0330607e0795d4b3247df51634ab2f

Add test for the no-husband case

---

requirements.txt

Change-Id: I3cda6c9f8c58291be8fada393acc06b2ae4ecaa1

requirements: pylint depends on these out of the box

---

README.adoc
TODO

Change-Id: I15b0e59c0298e9a42fdad23c44b9457461137599

Update user doc

---

TODO
ged2dot.py
ged2dotrc.sample
tests/test_ged2dot.py

Default to English style (given name first), but continue allowing
Hungarian style (family name first).
Change-Id: I94395fe5eceaf3879689939dda4635ccc26ea732

Support different name orders.

---

Makefile
inlineize.py

Change-Id: I59e471ce274bc4a7d25fb354a797bdf03f49c566

inlineize: add docstrings

---

TODO
libreoffice/HACKING
libreoffice/dialog.py
libreoffice/importer.py

This was lost with the bfs rewrite.
Change-Id: Idfa82fa01adf44bc741b2f57ddf3ae08d982c99c

Restore the lost libreoffice extension

---

Makefile
libreoffice/base.py
libreoffice/dialog.py
libreoffice/importer.py
libreoffice/loader.py

The suggestion to extract 2 functions from __to_svg() is great.
Change-Id: Ia9aa4bfc93b911d86ba542fe706d6665b7d102f4

libreoffice: fix pylint warnings

---

ged2dot.py
tests/test_ged2dot.py

Fixes <https://github.com/vmiklos/ged2dot/issues/19>.
Change-Id: I7c0aa57a71ea6a13c1c08beba7590356c8418ff0

Add Individual/Family __str__() functions for debugging

---

TODO
ged2dot.py
tests/test_ged2dot.py

Change-Id: I3f9e8d1ec2f787a42cf887480430e1b59c525b3c

Handle cmdline options

---

ged2dot.py
tests/test_ged2dot.py

Change-Id: Ic0d78c73565e62c8e9fb5cc897c591911044af68

Support reading input from stdin

---

ged2svg.sh

That automates the ged2dot, dot->svg -> linked-svg->inline-svg process.
Change-Id: Iecdcaf54d9efd8dea221361ba532aa57ad02d75c

Add a ged2svg script

---

.pylintrc
qt.py
requirements.txt

You can only set the input and output so far, nothing else.
Change-Id: I20367a15a923f297ce53c88fd7d4ea6c49b4f4a4

Import an initial pyqt-based GUI

---

Makefile

Change-Id: Ia14fef20d9cea911ed2642b367193d9705e515ef

qt: enforce linters

---

qt.py

Change-Id: Ib69a2585e0fc94e592e2f12f2178754d5d6de211

qt: add root family, image dir & name order selector

---

qt.py

So it won't be necessary to parse the text of items.
Change-Id: Ifa115db7231f3d0aa52b34d0162e1425409a5058

qt: set user data for family list

---

qt.py

Change-Id: I5aba09c944e59eb882894b436675c13fb6715c71

qt: extract setup_rootfamily() from main()

---

qt.py

Change-Id: I731ea50905d3787b02f31e628b7fdab1219ccd97

qt: extract setup_familydepth() from main()

---

qt.py

Change-Id: I8f4b0623aaa122464e7c7c6a8f49c65a39e0e8df

qt: extract setup_imagedir() & setup_nameorder() from main()

---

qt.py

Change-Id: I245c5d68257a8883ee5826d4ae275ef0813e663e

qt: implement conversion to .dot

---

qt.py

Change-Id: I58440aeb744235d035c882f613aad117b7cd30eb

qt: implement conversion to png

---

qt.py

Change-Id: Ia5b676a5efcdae498038d3928c010b4fbd453d04

qt: show backtrace when conversion fails

---

qged2dot.py

Change-Id: I5efa7fe0dc88736671f9eddfd75b7dcc4f56bc72

qged2dot: open result in a browser

---

requirements.txt

Change-Id: I00e91f65d9b9f09dfe09635f71f345f4d7112d52

requirements: add pyinstaller

---

Makefile

Change-Id: I8fba26cb8b51696d1f717b577b11a6bda0e517ea

qt: build a windowed installer, bundle dot

---

qged2dot.py

And also show exception whenever calling into ged2dot.py, which asserts
on bad user input.
Change-Id: I4a25c32b202faf8e17ab4c6a3ccc96f147ffdef8

qt: pass a URL to the webbrowser, not a path

---

Makefile

Change-Id: I87f312e8a5c48a0b6933f85fc51b2131e8a31290

qt: create .dmg on macOS

---

qged2dot.py

Change-Id: I33b084202be0b3ece384c06f3c64da46b33469ce

qt: add a status line & check for empty input/output

---

.github/workflows/tests.yml

Change-Id: Iec38d60383f83f7c29eeb6a2496fcf81b192abe8

CI: install python deps only once

---

README.adoc

Change-Id: I84b904441323d929b2a02a81fa8d5f86986b14b9

Update graphviz / macOS instructions

---

.github/workflows/tests.yml
tools/ci-build.sh

This will be useful later when it builds a .dmg for releases.
Change-Id: Ifd9f992e7d2c74f126788ed16cd4e71d09956ec2

CI: add a macOS builder

---

tools/ci-build.sh

Change-Id: I37bbc2276ea0c710da9d84625a676c3782f60af4

CI: generate a .dmg on macOS

---

.github/workflows/tests.yml

Change-Id: Ie7bb530e915a44cefd956607285f9dfc15a5aa4c

CI: upload macOS .dmg for tags

---

.github/workflows/tests.yml

Change-Id: I2146af4be4a3f283341f5d9f8de96c518eda069f

CI: run tests on branch/tag creation

---

Makefile

Change-Id: I6bfd03f72741e32cb1663d52dffc25a680f0de0b

make pack: include a version number in the output

---

.github/workflows/tests.yml
tools/ci-build.sh

Change-Id: I67fedbad4267d7e051b0e2bb568ac37fc2638322

CI: lock down the linux baseline

---

ged2dot.py
libreoffice/dialog.py
libreoffice/importer.py
qged2dot.py
tests/test_ged2dot.py

Avoids copy&pasting the same code 4 times
Change-Id: I2bb45affa773cca07497122b0ffa389890674276

Let load() also resolve the graph

---

HACKING.adoc
tools/pack.bat

Also add a Windows pack script, which does the ged->dot part, but then
executing dot doesn't work for some reason (invoking dot itself works
outside Python), needs more debugging.
Change-Id: I211c6846badcea47e622da9d9770479dc0d2ca1b

Update dev doc

---

tools/pack.bat

Still somewhat manual, but at least include enough dependencies so that
the png output of dot starts to work.
Change-Id: Idd0fe03e9f64a4fa46757d17304cb3c056253a5b

qged2dot: fix up windows packaging of dot

---

Makefile
libreoffice/Makefile
tools/ci-build.sh

Change-Id: Ie7a2f393b02724fc621e0920f8bd61eda170bbea

CI: build the LO extension on Linux

---

.github/workflows/tests.yml
NEWS.adoc
README.adoc

Change-Id: I308f880761c6fb95cb142f9a6feb592e671c8bef

CI: linux: deploy libreoffice extension

---

Makefile

Change-Id: I8919a0ca06c77b8a878e5cd82f119efd2470cf7b

ged2dot 7.1-rc2

---

Makefile
README.adoc
qged2dot.py
tools/ci-build.sh

Bundling the dynamic libraries is painful enough already, but then it
has its own plugin system, I gave up there.
Change-Id: Iaca115191e83c7ea859cfa417d8784e135e0e27d

qged2dot: give up on bundling dot

---

Makefile

Change-Id: Ia1e626f1e9abaf770dedd85094ce13122dc55df4

Version bump

---

qged2dot.py

Change-Id: I801dfe291e5df171bc030c0029e4be48123df544

qged2dot: fix dot binary path vs .dot input path

---

ged2dot.py
tests/multiline-note.ged
tests/test_ged2dot.py

Change-Id: Ic9bc9d26e70bbe4b8fff7dae5e65904b816794d6

Add testcase featuring multi-line notes

---

Makefile

Change-Id: I630f88c8b2fec160ad03f8f0e8568488fceaac9d

ged2dot 7.1-rc4

---

Makefile

Change-Id: I43572ae3ee3407183191036e152f9cd2fd2f0d9a

ged2dot 7.1-rc5

---

Makefile
tools/pack.py

Avoids some duplication and we'll be able to reuse part of that on
Windows.
Change-Id: Idb5ebb8e9022e73e5eb614112fa86915a54aecb7

make pack: turn some of the makefile into a python script

---

README.adoc
tools/pack.bat
tools/pack.py

To share code + can zip up the result this way.
Change-Id: I353467b6955448943967b020fdde65bc5ce621be

qged2dot: fold pack.bat into pack.py

---

.github/workflows/tests.yml
tools/ci-build.ps1

Change-Id: I050f91b2954cfdba542c40a8d750aed423150eb8

CI: add Windows job

---

Makefile
tools/pack.py

Has the benefit that the macos dmg has system/machine info in its name.
Change-Id: Ia27c1741c354e2e573a9c2a9b0e69a2dd556b2bd

pack: move hdiutil call into pack.py

---

tools/pack.py

darwin / amd64 may be confusing to users
Change-Id: I79f75572203d5691138b402b40548bf4aa22bc90

make pack: improve system/machine strings

---

msi/LICENSE.rtf
msi/qged2dot.json

Change-Id: Id785d199b8c84fa64a0a4955f2786f56f42630a0

qged2dot, windows: add static files towards msi creation

---

tools/ci-build.ps1

Change-Id: I8d4593432fcf80d5654de42106cf2d60228887c0

qged2dot, windows: install wixtools/msicreator during CI

---

tools/ci-build.sh
tools/pack.py

And also run msicreator, finally rename it to be in sync with the macos
naming.
Change-Id: I94a384fa3611e157a4cce451335943c917613026

qged2dot, windows: generate msi template

---

tools/pack.py

Change-Id: I79d6314291a1cba680b4fb752183e366be7a8603

qged2dot, windows: log msi name

---

.github/workflows/tests.yml

Change-Id: I86e3a1eb48a4c5c358f8c356f3b7559b90260184

CI: windows: zip -> msi

---

Makefile

Change-Id: I164af9619791947c6b4e0cd769e864b6987e4670

ged2dot 7.1-rc8

---

requirements.txt

Change-Id: If1848751e0584ae12ac1704e4dea53e27241c9aa

requirements: update coverate to 5.4

---

qged2dot.py
tools/ci-build.ps1
tools/pack.py

Based on pyinstaller/pyinstaller/issues/4938.
Change-Id: I60481b151a592cb7c740c107cb9191ae4198ea9d

CI: Windows: bundle graphviz

---

README.adoc
requirements.txt

Change-Id: Iee06541f92584edeb1a31901526b2a25cc48a47f

Update qged2dot.msi doc

---

qged2dot.py
tools/ci-build.sh
tools/pack.py

I gave up on this already once, but seeing it's working on Windows...
The Windows case is easier though, since the choco-provided Graphviz is
self-contained.
Change-Id: I646b40272e916b438206b1eba4952b742996c43b

CI: macOS: bundle graphviz

---

requirements.txt

Change-Id: I80c5233a9b157ba8b4604c0fbdbe0678bb5d7f06

requirements: update pyinstaller to 4.2

---

README.adoc

Change-Id: Id1042d385ced73a4490056904c3250689c1827db

qged2dot: update macOS doc

---

pyi/hook-pygraphviz.py
requirements.txt
tools/ci-build.ps1
tools/ci-build.sh

So that dot bundling can be pyinstaller's problem in the long run. Just
add the dependency, don't start using it yet.
Change-Id: Id7d8a9c454edb9521ed7b18c75b783ece260c10e

qged2dot: depend on pygraphviz

---

qged2dot.py
tools/pack.py

Allows removing the own dot bundling code.
Change-Id: I4703cecbf1d94af67dcf3f10cc915e786566982c

qged2dot: use pygraphviz

---

Makefile
NEWS.adoc
README.adoc

Change-Id: Ied2f55112e78929ea91ad74de5e3892d4a27f799

ged2dot 7.1

---

pyi/hook-pygraphviz.py

src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pygraphviz.py in
pyinstaller-hooks-contrib.git.
Change-Id: I6a7c840ee572a377e617eb2b1939871d11781db5

Update hook-pygraphviz.py to how it was upstreamed

---

qged2dot.py

So people who want all the benefits/complexity of a vector-based output
can have it.
Change-Id: Ide8ca965cea28fd6d74ed0efbc1460d667322cb8

qged2dot: allow converting to svg

---

requirements.txt

Change-Id: Id99625f90ed77ec04c411094faaf3fd41d3c3a61

requirements: update mypy to 0.812

---

pyi/hook-pygraphviz.py

Change-Id: I044b8f2b22ce626569e52eac0355988d37348b0e

pyinstaller: only bundle an explicit list of binaries

---

pyi/hook-pygraphviz.py
tools/ci-build.ps1

Which works for me locally, but not during CI, where the directory name
doesn't contain the version. And that failure is interestingly
non-fatal...
Change-Id: Ic39a6bfe1f05c5e6ea6346a00f06b66570f0d5b9

CI: try to fix pygraphviz install on Windows

---

requirements.txt

Change-Id: I30830eb01a1dbe7be9b46eb03db4da403026f1ab

requirements: update pylint to 2.7.2

---

pyi/hook-pygraphviz.py

Change-Id: I1fd179082c71e0bd040dc0e65733e5a6c8a56dfd

Add Linux support to hook-pygraphviz.py

---

tools/ci-build.ps1

<https://stackoverflow.com/questions/9948517/how-to-stop-a-powershell-script-on-the-first-error>
says there is no easy 'bash -e' equivalent, so this do this manually.
Change-Id: I708d56c0cb3b9a8f1f3172616cd13c40f6c4eb44

CI: add Windows error handling

---

pyi/hook-pygraphviz.py

Change-Id: Iac430776d7b7dad69efe5906219b74183f487e50

Add Linux lib64 support to hook-pygraphviz.py

---

requirements.txt

Change-Id: I95d782735b1b2abcbc8a3c1a0caf0ab11d52e17d

requirements: update coverage to 5.5

---

qged2dot.py
requirements.txt

Which adds type hints, it seems.
Change-Id: I902d334051ef02fbc9b939017da6809b3fe93bfe

requirements: pyqt5 to 5.15.4

---

requirements.txt

Change-Id: Ic43f037ce832ef5d05b6ad53be25df935f3be446

requirements: update flake8 to 3.9.0

---

requirements.txt

Change-Id: I282d744bc7b53282d149d6be429af5f60c0675cf

requirements: update pylint to 2.7.4

---

requirements.txt

Change-Id: I5e231632c8090ec69c49b8afe88a4c975af25401

requirements: update flake8 to 3.9.1

---

requirements.txt

Change-Id: Idc2278d321ed43c3e26fde1fef3fb8ad1f41b085

requirements: update pyinstaller to 4.3

---

inlineize.py
libreoffice/base.py
libreoffice/importer.py
requirements.txt

Change-Id: I8777dba8d114e0ea15888146972e22cd9fac32a7

Use 'with' for resource-allocating operations

---

requirements.txt

Change-Id: I4122bb83795c59c30195121051cbd4979db6ccb0

Update flake8 to 3.9.2

---

requirements.txt

Change-Id: I33279656c2a985604258761a898a3b6201706761

Update pylint to 2.8.3

---

requirements.txt

Change-Id: Iad509d2187e3267b2a22972766b6db5975c247d9

Update mypy to 0.902

---

NEWS.adoc
ged2dot.py
tests/test_ged2dot.py

Note that this only works when the output is not stdout.
This is 2) of <https://github.com/vmiklos/ged2dot/issues/170>.
Change-Id: I121accdef2b4efc5bbc27750b4c4c42b9ff8329f

Add a new --relpath option

---

ged2dot.py
tools/ci-build.ps1
tools/pack.py

Change-Id: Ic7178fc9f6f5dc7b5e71cadd55b3564ee7fe0c9f

GedcomImport: fix a typo

---

requirements.txt

Change-Id: I387eed813ee94f57d2c2f76dff34e4823a2d6e37

requirements: update coverage to 6.2

---

requirements.txt

Change-Id: Ic9a6644ce034a287433d41cbf018fe1665a20c66

requirements: update flake8 to 4.0.1

---

ged2dot.py

Attempt to fallback on "first lastname.jpg" if "first lastname birth-year.jpg" does not exist, before relying on placeholders.

Image search fallback

---

ged2dot.py
inlineize.py
libreoffice/base.py
libreoffice/dialog.py
libreoffice/importer.py
qged2dot.py
requirements.txt
tests/test_ged2dot.py
tests/test_inlineize.py
tools/pack.py

Change-Id: Ib6d19605a7cbb560f135aed2b5c00b253acae1f9

Update pylint to 2.12.2

---

requirements.txt

Change-Id: Icb734d2cedb9f7c6bedeb1d6e2d06b3ca1855e90

requirements: update pyinstaller to 4.7

---

Makefile
requirements.txt

Change-Id: Ia225a8cd1fd936d0000ea814e3a238e9c0387d3c

requirements: update mypy to 0.930

---

requirements.txt

Change-Id: I00f9058face7e63990905a068bdc4b17c23385db

requirements: update pyqt5 to 5.15.6

---

requirements.txt

Change-Id: I6aac39771e1d7132e503b449392f822c6d088bbe

requirements: update pyinstaller to 4.8

---

requirements.txt

Change-Id: Iaf294f352a5800ee271044ec55c1ba9161447099

requirements: update mypy to 0.931

---

README.adoc

Change-Id: I110d1e27d66560ce62f7c5fa6c62c3b42c708fbd

README: link ged2dot.js

---

Makefile
NEWS.adoc
README.adoc

Change-Id: I0d717df0370f02d13a98226933200c0c88178c29

ged2dot 7.3

---

requirements.txt

Change-Id: Idb1c4814952951c7775994fe7d75d90afb30d6b3

requirements: update pyinstaller to 4.9

---

README.adoc

Fixes <https://github.com/vmiklos/ged2dot/issues/202>.
Change-Id: Iacfaf7f45c51de3a727c8711cdf9ed3f8b050f90

Document expected image location

---

ged2dot.py
requirements.txt

As pointed out by the new pylint.
Change-Id: I70550ba4789d03206ead1a5e5f1b2c81a9dabd84

Remove unnecessary ellipsis constants

---

requirements.txt

Change-Id: I7d467b584020d41b374e1b3f265e9b11aab576f7

requirements: update coverage to 6.3.2

---

requirements.txt

Change-Id: Ic117f4bcd70257ad12dda214d600e64c53c6a926

requirements: update mypy to 0.950

---

requirements.txt

Change-Id: Ia04418f65e707a7f3a3160b9d2d20f0538995852

requirements: update pygraphviz to 1.9

---

requirements.txt

Change-Id: Idefb82146b6138c890333761cf0fbd8aa8295c35

requirements: update coverage to 6.3.3

---

requirements.txt

Change-Id: I557babe882459cc10964ea01ec327f17c1b29816

requirements: update mypy to 0.960

---

Makefile
ged2dot.py
requirements.txt

Change-Id: I448301083599157bdeaa712e130a33b0d2776b32

requirements: update pylint to 2.14.0

---

requirements.txt

Change-Id: Ia35b0fd2f2d33346af08f456d32635e90054a834

Update pyinstaller to 5.1

---

Makefile
qged2dot.py
requirements.txt

Change-Id: I3469e89618e1f8e27f9948c8a21d9e4ceb9c29ac

Update to pyqt5 5.15.7

---

requirements.txt

Change-Id: I4528ce34aee44035749ae8ac2b6d445e006d7cdd

requirements: update coverage to 6.4.1

---

.github/workflows/tests.yml
HACKING.adoc
requirements.txt

And document what's the replacement for piprot
Change-Id: Iaf4c0f9e88c610378eb1a28c4d2a2d31e74d3e3b

Update mypy to 0.961

---

Makefile
NEWS.adoc
README.adoc

Change-Id: Ida851c696d3e5f37ffa4abb84daabb73ed0a3f30

ged2dot 7.4

---

requirements.txt

Change-Id: I634c992d083106bf3a5470c9f3303831025ab80d

Update coverage to 6.4.2

---

requirements.txt

Change-Id: I1a909e7bae390c594c223490b1ada263bdbd27c9

Update flake8 to 5.0.4

---

.github/workflows/tests.yml

Change-Id: Ia19cf342f206b31df00bdd965f1347026f9db18e

CI: use ubuntu-22.04 as Linux baseline

---

.github/workflows/tests.yml

Change-Id: I32f2e946c04b2721c91e6cbf38db7201a9dd7b14

CI: use windows-2022 as Windows baseline

---

requirements.txt

Change-Id: I5393081f211627f236de302b3c3117bd3d838571

Update pyinstaller to 5.3

---

requirements.txt
tools/ci-build.ps1

Change-Id: I11129f9ff2ab75632b424b7c4a009dafbc9b968f

Update pygraphviz to 1.10

---

requirements.txt

Change-Id: Ic122a2b47341a81d7eb79b5632dc34df9830fcc5

Update mypy to 0.971

---

requirements.txt

Change-Id: Iadae74785ef50cf4395547d9cba3637b6ffc679a

requirements: update coverage to 6.5.0

---

requirements.txt

Change-Id: Ic5f8177d6c348e1333169fd039487aae44d62071

Update mypy to 0.982

---

ged2dot.py
requirements.txt
tools/pack.py

Change-Id: I4bb9802f5660646e5cc460069267a6ba5fd401bc

Update dependencies (2022-12)

---

NEWS.md
README.adoc

Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: I6bf5997947cec7c9dcb95b1b77f5057d79bfd7f8

NEWS: convert this to markdown

---

README.md

Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: Ifb33ad284b49cbb18df5d41e6496876b036b2de6

README: convert this to markdown

---

README.md

Change-Id: I8b91eea0164de447dd3f8d45475df1ed104c4740

README.md: finish conversion from asciidoc

---

HACKING.md

Towards merging the documentation and the website into a single,
markdown-based guide.
Change-Id: I4a2e6c2feacb0190bc123c51554d6902a2250548

HACKING: convert this to markdown

---

requirements.txt

Change-Id: I94d3a713ba20b83cbd5ae037be2d6f10bc9285d6

Update dependencies (2023-01)

---

guide/src/README.md
guide/src/usage.md
requirements.txt

This used to work with the old asciidoc README.
Change-Id: I974137b53a924972eec55c0e0f579ffa95303302

guide: move one screenshot to the front page

---

guide/src/README.md
guide/src/usage.md

The itention isn't to offend the <https://gramps-project.org/> guys.
Also replace some "->" with "→", markdown doesn't do autocorrect like
asciidoc did.
Change-Id: I19e23cd57c87963d8851e736910d74f9ef8508e0

guide: random -> other existing

---

Makefile
guide/src/news.md

Change-Id: Ide866455e96890b30f5b99d7cc3779e2e0b8fb50

ged2dot 7.5

---

guide/src/README.md

Change-Id: If540249bae6d64b500a98aecdde168cbfb83850e

guide: update release version & date

---

ged2dot.py
libreoffice/importer.py
requirements.txt

Change-Id: Id4351b24ea9fffaccca7296bfa8e56e3f948152e

Update dependencies (2023-02)

---

guide/src/hacking.md
tests/test_ged2dot.py

Replace assertIn() with proper pygraphviz + XML parsing.
Change-Id: I661f7279655647f13998195d4b379089399fdca3

Improve test_ged2dot.TestMain.test_happy

---

.github/workflows/tests.yml

Change-Id: Ife2fe2ac2773aabbb0afc391b31415d2f1f537df

CI: update to macos-12

---

ged2dot.py
ged2svg.sh
inlineize.py
libreoffice/Makefile
libreoffice/base.py
libreoffice/dialog.py
libreoffice/importer.py
libreoffice/loader.py
qged2dot.py
tests/test_ged2dot.py
tests/test_inlineize.py
tools/ci-build.ps1
tools/ci-build.sh
tools/pack.py
tools/requirements.py

Less boilerplate.
Change-Id: Ibbbe8b1d0be592b908483b7bc65732e0458683c2

Switch to SPDX-style license identifiers

---

requirements.txt

Change-Id: I27e22efcd25ba4fd8971fc248fba09d92ba1f801

Update dependencies (2023-04)

---

requirements.txt
tools/ci-build.ps1

Change-Id: Ic91b2de5a4cb4fc3e5e3dd238804af0b34cca324

Update dependencies (2023-06)

---

.github/workflows/tests.yml

Change-Id: I2ecf60bad436eed798bf9c822a23dabfe8811c98

CI: update to Python 3.11

---

ged2dot.py

Where 'from' would be a Python keyword.
Change-Id: Idca80582f96acfcdb84f9632859e475f98079fda

Drop one 'fro' workaround

---

requirements.txt

Change-Id: Id8b95c3d311f2f07b742df14b97a3c9f73ef5b9e

Update dependencies (2023-07)

---

Makefile
guide/src/README.md
guide/src/news.md

Change-Id: I2b78369145d092fb983c54a8e73cf0e7a016e98c

ged2dot 7.6

---

requirements.txt

Change-Id: I1e1c0abbd860407ff2fb50186bfc4fea84c567cf

Update dependencies (2023-09)

---

.github/workflows/tests.yml

Change-Id: I97dbf7d4ac7fc2bbb4c035c7ae6ec603c391e883

CI: update to macOS 13

---

.github/workflows/tests.yml

Change-Id: Id86875844e5ed50acf654651c5dcf4114d935cdd

CI: update actions/checkout to v4.0.0

---

requirements.txt

Change-Id: If9119c5e10c83a33d9563a4ae31ad5d3ed652625

Update dependencies (2023-10)

---

requirements.txt

Change-Id: I817734a938ed5068e5a6bb53632b3dd2685e308e

Update dependencies (2023-11)

---

.github/workflows/tests.yml

Change-Id: If6b111517e57955caaf86a8c3ae548a399d04e0f

CI: update checkout to v4.1.1

---

ged2dot.py
guide/src/news.md
tools/ci-build.sh

This is good enough in practice, but later we may want to also sort the
kids by their birth date.

Use ordering=out on family nodes to try to control the order of children nodes

---

.pylintrc
Makefile
qged2dot.py
requirements.txt
tools/ci-build.sh

Allows getting rid of some 6 pylint warnings.

Update to pyqt6

---

.github/workflows/tests.yml
Makefile
guide/src/installation.md
libreoffice/install
tools/ci-build.sh
tools/pack.py

I no longer have the HW to debug problems if something fails.

Remove macOS support

---

ged2dot.py

This keeps them together in the layout whereas withotu this change spouses can be arbitrarily far apart.

Put spouses (labelled as married) into a subgraph cluster
